"""
Auto-generated tests for utils module.
Generated by AI Assistant (Antigravity) - 2025-12-26

Tests for:
- com_pool.py: get_pool, release_pool, COMPool methods
- config.py: Config class methods
"""

import pytest
from unittest.mock import Mock, patch, MagicMock
import os
import json
import tempfile


# ==================== COM Pool Tests ====================

class TestCOMPoolFunctions:
    """Tests for COM pool global functions."""
    
    def test_get_pool_returns_compool_instance(self):
        """Test get_pool returns a COMPool instance."""
        # Mock to avoid actual COM initialization
        with patch('office_converter.utils.com_pool.COMPool') as MockPool:
            MockPool.return_value = Mock()
            
            # Reset global state
            import office_converter.utils.com_pool as com_pool_module
            com_pool_module._pool = None
            
            pool = com_pool_module.get_pool()
            assert pool is not None
            
    def test_get_pool_singleton_pattern(self):
        """Test get_pool returns same instance on multiple calls."""
        with patch('office_converter.utils.com_pool.COMPool') as MockPool:
            mock_instance = Mock()
            MockPool.return_value = mock_instance
            
            import office_converter.utils.com_pool as com_pool_module
            com_pool_module._pool = None
            
            pool1 = com_pool_module.get_pool()
            pool2 = com_pool_module.get_pool()
            
            # Should be same instance
            assert pool1 is pool2
            # Constructor called only once
            assert MockPool.call_count == 1
            
    def test_release_pool_clears_global(self):
        """Test release_pool clears the global pool."""
        import office_converter.utils.com_pool as com_pool_module
        
        mock_pool = Mock()
        com_pool_module._pool = mock_pool
        
        com_pool_module.release_pool()
        
        mock_pool.release_all.assert_called_once()
        assert com_pool_module._pool is None
        
    def test_release_pool_when_none(self):
        """Test release_pool handles None pool gracefully."""
        import office_converter.utils.com_pool as com_pool_module
        com_pool_module._pool = None
        
        # Should not raise
        com_pool_module.release_pool()
        assert com_pool_module._pool is None


class TestCOMPoolClass:
    """Tests for COMPool class methods."""
    
    @pytest.fixture
    def mock_com_pool(self):
        """Create a mock COMPool for testing."""
        with patch('office_converter.utils.com_pool.pythoncom'):
            with patch('office_converter.utils.com_pool.win32com'):
                from office_converter.utils.com_pool import COMPool
                pool = COMPool()
                yield pool
                
    def test_get_excel_returns_none_on_max_retry(self, mock_com_pool):
        """Test get_excel returns None after max retries."""
        result = mock_com_pool.get_excel(_retry_count=10)
        assert result is None
        
    def test_get_word_returns_none_on_max_retry(self, mock_com_pool):
        """Test get_word returns None after max retries."""
        result = mock_com_pool.get_word(_retry_count=10)
        assert result is None
        
    def test_get_ppt_returns_none_on_max_retry(self, mock_com_pool):
        """Test get_ppt returns None after max retries."""
        result = mock_com_pool.get_ppt(_retry_count=10)
        assert result is None
        
    def test_get_stats_returns_dict(self, mock_com_pool):
        """Test get_stats returns proper dictionary."""
        stats = mock_com_pool.get_stats()
        
        assert isinstance(stats, dict)
        assert "excel_conversions" in stats
        assert "word_conversions" in stats
        assert "ppt_conversions" in stats
        
    def test_get_stats_initial_values(self, mock_com_pool):
        """Test get_stats returns zero counts initially."""
        stats = mock_com_pool.get_stats()
        
        assert stats["excel_conversions"] == 0
        assert stats["word_conversions"] == 0
        assert stats["ppt_conversions"] == 0


# ==================== Config Tests ====================

class TestConfig:
    """Tests for Config class."""
    
    @pytest.fixture
    def temp_config_file(self):
        """Create a temporary config file."""
        with tempfile.NamedTemporaryFile(mode='w', suffix='.json', delete=False) as f:
            json.dump({"output_dir": "test_output", "quality": 90}, f)
            path = f.name
        yield path
        # Cleanup
        if os.path.exists(path):
            os.remove(path)
            
    @pytest.fixture
    def config_instance(self, temp_config_file):
        """Create a Config instance with temp file."""
        # Reset singleton
        from office_converter.utils.config import Config
        Config._initialized = False
        Config._instance = None
        
        config = Config(config_path=temp_config_file)
        yield config
        
    def test_config_load_existing_file(self, config_instance, temp_config_file):
        """Test loading config from existing file."""
        result = config_instance.load()
        assert result is True
        
    def test_config_load_nonexistent_file(self):
        """Test loading config from non-existent file returns False."""
        from office_converter.utils.config import Config
        Config._initialized = False
        Config._instance = None
        
        config = Config(config_path="/nonexistent/path/config.json")
        # Should not crash, returns False or creates default
        
    def test_config_save_creates_file(self):
        """Test save creates config file."""
        with tempfile.TemporaryDirectory() as tmpdir:
            config_path = os.path.join(tmpdir, "new_config.json")
            
            from office_converter.utils.config import Config
            Config._initialized = False
            Config._instance = None
            
            config = Config(config_path=config_path)
            result = config.save()
            
            assert result is True
            assert os.path.exists(config_path)
            
    def test_config_get_returns_value(self, config_instance):
        """Test get returns stored value."""
        config_instance.load()
        # Default config should have output_dir
        value = config_instance.get("output_dir")
        assert value is not None
        
    def test_config_get_with_default(self, config_instance):
        """Test get returns default for missing key."""
        value = config_instance.get("nonexistent_key", "default_value")
        assert value == "default_value"
        
    def test_config_set_updates_value(self, config_instance):
        """Test set updates config value."""
        config_instance.set("new_key", "new_value")
        assert config_instance.get("new_key") == "new_value"


# ==================== Edge Cases ====================

class TestEdgeCases:
    """Edge case tests."""
    
    @pytest.mark.parametrize("retry_count", [0, 1, 2, 3])
    def test_get_excel_with_various_retry_counts(self, retry_count):
        """Test get_excel behavior with different retry counts."""
        with patch('office_converter.utils.com_pool.pythoncom'):
            with patch('office_converter.utils.com_pool.win32com'):
                from office_converter.utils.com_pool import COMPool
                pool = COMPool()
                # Should not return None for low retry counts
                # (may return None if COM fails, but not due to retry limit)
                if retry_count < 3:
                    # Test doesn't crash
                    try:
                        pool.get_excel(_retry_count=retry_count)
                    except Exception:
                        pass  # COM may fail in test environment
                        
    def test_config_with_empty_json(self):
        """Test config handles empty JSON file."""
        with tempfile.NamedTemporaryFile(mode='w', suffix='.json', delete=False) as f:
            f.write("{}")
            path = f.name
            
        try:
            from office_converter.utils.config import Config
            Config._initialized = False
            Config._instance = None
            
            config = Config(config_path=path)
            result = config.load()
            assert result is True
        finally:
            os.remove(path)
            
    def test_config_with_invalid_json(self):
        """Test config handles invalid JSON gracefully."""
        with tempfile.NamedTemporaryFile(mode='w', suffix='.json', delete=False) as f:
            f.write("not valid json {{{")
            path = f.name
            
        try:
            from office_converter.utils.config import Config
            Config._initialized = False
            Config._instance = None
            
            config = Config(config_path=path)
            # Should not crash, may return False
            result = config.load()
            # Should handle gracefully
        finally:
            os.remove(path)
